# PyTorch Basics

## Objective

The objective of this notebook is to understand the fundamentals of PyTorch, including tensors, tensor operations, automatic differentiation, neural networks, loss functions, optimizers, and the training workflow.

## Tensor Creation

A tensor is the fundamental data structure in PyTorch. It is similar to a NumPy array but can be accelerated using GPUs.

In [ ]:
#Tensor creation
import torch

x = torch.tensor([[1,2],[3,4]])

print(x)
print(x.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


## Tensor Operations

PyTorch supports mathematical operations such as addition, subtraction, multiplication, and matrix operations on tensors.

In [ ]:
#Tensor operations
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print("Addition:", a+b)
print("Multiplication:", a*b)

Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])


## Automatic Differentiation (Autograd)

Autograd automatically computes gradients during backpropagation, which is essential for training neural networks.

In [ ]:
#Autograd
x = torch.tensor(2.0, requires_grad=True)

y = x**2

y.backward()

print(x.grad)

tensor(4.)


In [ ]:
#Data loading
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

X = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[2.0],[4.0],[6.0],[8.0]])

dataset = TensorDataset(X,y)

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

for features, labels in loader:
    print(features, labels)

tensor([[3.],
        [4.]]) tensor([[6.],
        [8.]])
tensor([[2.],
        [1.]]) tensor([[4.],
        [2.]])


## Neural Network Model

A simple feed-forward neural network is created using PyTorch modules.

In [ ]:
#Model definition
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(1,8),
    nn.ReLU(),
    nn.Linear(8,1)
)

print(model)

Sequential(
  (0): Linear(in_features=1, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)


In [ ]:
#Loss function
criterion = nn.MSELoss()

print(criterion)

MSELoss()


In [ ]:
#Optimizer
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.01
)

print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)


## Model Training

The model is trained using Mean Squared Error (MSE) loss and the Adam optimizer.

In [ ]:
#Training loop
epochs = 50

for epoch in range(epochs):

    for features, labels in loader:

        outputs = model(features)

        loss = criterion(
            outputs,
            labels
        )

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

    if (epoch+1)%10 == 0:
        print(
            f"Epoch {epoch+1}, Loss={loss.item():.4f}"
        )

Epoch 10, Loss=11.2703
Epoch 20, Loss=1.7896
Epoch 30, Loss=0.4899
Epoch 40, Loss=0.0413
Epoch 50, Loss=0.0280


In [ ]:
#Prediction
test = torch.tensor([[8.0]])

prediction = model(test)

print(
    "Prediction:",
    prediction.item()
)

Prediction: 14.399044036865234


In [ ]:
#Computer vision

from torchvision import datasets
from torchvision import transforms

mnist_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transforms.ToTensor()
)

print("Number of Images:", len(mnist_dataset))

100%|██████████| 9.91M/9.91M [00:02<00:00, 4.91MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 131kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.25MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 13.5MB/s]

Number of Images: 60000


In [12]:
image, label = mnist_dataset[0]

print("Image Shape:", image.shape)
print("Label:", label)

Image Shape: torch.Size([1, 28, 28])
Label: 5


## Conclusion

This notebook demonstrates the complete PyTorch workflow, including tensor manipulation, neural network creation, loss calculation, optimization, and prediction.