# PyTorch Basics

## Objective

The objective of this notebook is to understand the fundamentals of PyTorch, including tensors, tensor operations, automatic differentiation, neural networks, loss functions, optimizers, and the training workflow.

## Tensor Creation

A tensor is the fundamental data structure in PyTorch. It is similar to a NumPy array but can be accelerated using GPUs.

In [ ]:
# Import the PyTorch library
import torch

# Create a 2D tensor (matrix) with shape (2, 2) from a nested list
x = torch.tensor([[1,2],[3,4]])

# Print the tensor values
print(x)
# Print the shape of the tensor (dimensions)
print(x.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


## Tensor Operations

PyTorch supports mathematical operations such as addition, subtraction, multiplication, and matrix operations on tensors.

In [ ]:
# Define two 1D tensors (vectors) of size 3
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

# Perform element-wise addition of tensors a and b
print("Addition:", a+b)
# Perform element-wise multiplication of tensors a and b
print("Multiplication:", a*b)

Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])


## Automatic Differentiation (Autograd)

Autograd automatically computes gradients during backpropagation, which is essential for training neural networks.

In [ ]:
# Create a scalar tensor and enable gradient tracking with requires_grad=True
x = torch.tensor(2.0, requires_grad=True)

# Define a function y = x^2
y = x**2

# Compute the gradients using backward pass (backpropagation)
y.backward()

# Print the gradient of y with respect to x (dy/dx = 2*x = 4.0)
print(x.grad)

tensor(4.)


In [ ]:
# Import utility classes for dataset wrapping and mini-batch loading
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

# Create features tensor X and targets tensor y (representing y = 2*X)
X = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[2.0],[4.0],[6.0],[8.0]])

# Wrap the tensors into a PyTorch Dataset
dataset = TensorDataset(X,y)

# Create a DataLoader to iterate over the dataset in shuffled batches of size 2
loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

# Loop through dataloader to fetch and print mini-batches of features and labels
for features, labels in loader:
    print(features, labels)

tensor([[3.],
        [4.]]) tensor([[6.],
        [8.]])
tensor([[2.],
        [1.]]) tensor([[4.],
        [2.]])


## Neural Network Model

A simple feed-forward neural network is created using PyTorch modules.

In [ ]:
# Import the PyTorch neural network module
import torch.nn as nn

# Define a simple feed-forward neural network using Sequential container
model = nn.Sequential(
    # Linear input layer mapping 1 feature to 8 hidden units
    nn.Linear(1,8),
    # Non-linear activation function ReLU
    nn.ReLU(),
    # Linear output layer mapping 8 hidden units back to 1 output value
    nn.Linear(8,1)
)

# Display the model architecture details
print(model)

Sequential(
  (0): Linear(in_features=1, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)


In [ ]:
# Define the Mean Squared Error (MSE) loss criterion for regression
criterion = nn.MSELoss()

# Print the loss function type
print(criterion)

MSELoss()


In [ ]:
# Initialize the Adam optimizer to update model parameters with learning rate of 0.01
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.01
)

# Display optimizer configurations
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)


## Model Training

The model is trained using Mean Squared Error (MSE) loss and the Adam optimizer.

In [ ]:
# Set the number of training epochs
epochs = 50

# Iterate over the specified number of training epochs
for epoch in range(epochs):

    # Retrieve mini-batches from the data loader
    for features, labels in loader:

        # Run the forward pass to get predictions
        outputs = model(features)

        # Calculate the loss between predictions and actual targets
        loss = criterion(
            outputs,
            labels
        )

        # Clear the gradients of all optimized variables before backpropagation
        optimizer.zero_grad()

        # Run backpropagation to compute gradients
        loss.backward()

        # Perform a single optimization step to update parameters
        optimizer.step()

    # Print loss value every 10 epochs
    if (epoch+1)%10 == 0:
        print(
            f"Epoch {epoch+1}, Loss={loss.item():.4f}"
        )

Epoch 10, Loss=11.2703
Epoch 20, Loss=1.7896
Epoch 30, Loss=0.4899
Epoch 40, Loss=0.0413
Epoch 50, Loss=0.0280


In [ ]:
# Create a test input tensor for prediction
test = torch.tensor([[8.0]])

# Get prediction output from the trained network (forward pass)
prediction = model(test)

# Print the predicted scalar value
print(
    "Prediction:",
    prediction.item()
)

Prediction: 14.399044036865234


In [ ]:
# Import datasets and transforms from torchvision for computer vision tasks
from torchvision import datasets
from torchvision import transforms

# Download and load the MNIST training dataset, converting images to float tensors
mnist_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transforms.ToTensor()
)

# Print total count of samples in dataset
print("Number of Images:", len(mnist_dataset))

100%|██████████| 9.91M/9.91M [00:02<00:00, 4.91MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 131kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.25MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 13.5MB/s]

Number of Images: 60000


In [12]:
# Extract the first image tensor and its corresponding ground truth label
image, label = mnist_dataset[0]

# Display the dimensions of the image tensor (Channels, Height, Width)
print("Image Shape:", image.shape)
# Print class label of the digit image
print("Label:", label)

Image Shape: torch.Size([1, 28, 28])
Label: 5


## Conclusion

This notebook demonstrates the complete PyTorch workflow, including tensor manipulation, neural network creation, loss calculation, optimization, and prediction.